# Add account details to api_urls if need be

title = "Tag Injector Configuration"


[[Booru]]

    name = 'Gelbooru'

    api_url = 'https://gelbooru.com/index.php?limit=1&page=dapi&s=post&q=index&tags=md5%3a'
    
    tag_regex = '<tags>(.+)</tags>'

[[Booru]]

    name = 'Danbooru'

    api_url = 'https://danbooru.donmai.us/posts.xml?limit=1&tags=md5%3A'

    tag_regex = '<tag-string>(.+)</tag-string>'

[[Booru]]

    name = 'Yandere'

    api_url = 'https://yande.re/post.xml?limit=1&tags=md5%3A'

    tag_regex = 'tags="([^"]+)'

