# Tag Injector Configuration

# Add account details to api_urls if need be


[[boards]]

    name = 'Gelbooru'

    api_url = 'https://gelbooru.com/index.php?limit=1&page=dapi&s=post&q=index&tags=md5%3a'
    
    tag_regex = '<tags>(.+)</tags>'

[[boards]]

    name = 'Danbooru'

    api_url = 'https://danbooru.donmai.us/posts.xml?login=damaskpear&api_key=4CABdoRQfTKmYbChEyJsLswB&limit=1&tags=md5%3A'

    tag_regex = '<tag-string>(.+)</tag-string>'

[[boards]]

    name = 'All The Fallen'

    api_url = 'https://booru.allthefallen.moe/posts.xml?limit=1&tags=md5%3A'

    tag_regex = '<tag-string>(.+)</tag-string>'

[[boards]]

    name = 'Rule34xxx'

    api_url = 'https://api.rule34.xxx/index.php?limit=1&page=dapi&s=post&q=index&tags=md5%3a'
    
    tag_regex = 'tags="([^"]+)'


[[boards]]

    name = 'Yandere'

    api_url = 'https://yande.re/post.xml?limit=1&tags=md5%3A'

    tag_regex = 'tags="([^"]+)'

